language: node_js
node_js:
- '6.10.0'
install:
    - npm install -g codecov
services:
- mongodb
cache:
  directories:
    - node_modules
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    branch: release
  bucket: team-ignition
  region: us-west-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: team-ignition
  key: latest.zip
  bundle_type: zip
  application: operation-ignition
  deployment_group: ignition-servers
  region: us-west-2
  on: *2